<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use RuntimeException;

class ObrasCivilesTrabajadoresSeeder extends Seeder
{
    public function run(): void
    {
        DB::transaction(function () {
            $now = now();

            // Si tu campo estado es tinyint/boolean, cambia 'activo' por 1.
            $estadoActivo = 'activo';

            $proyectoNombre = 'Proyecto Obras Civiles';

            DB::table('proyectos')->updateOrInsert(
                ['nombre' => $proyectoNombre],
                [
                    'activo' => 1,
                    'created_at' => $now,
                    'updated_at' => $now,
                ]
            );

            $proyecto = DB::table('proyectos')
                ->whereRaw('LOWER(nombre) LIKE ?', ['%obras civiles%'])
                ->first();

            if (! $proyecto) {
                throw new RuntimeException('No se encontró el proyecto Obras Civiles.');
            }

            $cargos = [
                'Ayudante Civil',
                'Oficial Civil',
                'Operario Civil',
                'Almacenero',
                'Capataz',
                'Chofer',
                'Asistente Administrativo',
                'Supervisor de Obras Civiles',
                'Supervisor de Seguridad',
                'ingeniero Residente',
            ];

            foreach ($cargos as $cargo) {
                DB::table('cargos_laborales')->updateOrInsert(
                    ['nombre' => $cargo],
                    [
                        'created_at' => $now,
                        'updated_at' => $now,
                    ]
                );
            }

            $normalizar = fn ($valor) => Str::lower(Str::squish(Str::ascii($valor)));

            $cargoIds = DB::table('cargos_laborales')
                ->get(['id', 'nombre'])
                ->mapWithKeys(fn ($cargo) => [
                    $normalizar($cargo->nombre) => $cargo->id,
                ]);

            $trabajadores = [
                [
                    'codigo_fotocheck' => 'GC0000003',
                    'dni' => '73067972',
                    'nombres' => 'EDUARDO HUMBERTO',
                    'apellidos' => 'ZAMORA LA TORRE',
                    'correo' => 'eduardo.zamora@grupocredco.com',
                    'telefono' => '961792237',
                    'happy_birthday' => '1995-09-12',
                    'fecha_ingreso' => '2021-03-03',
                    'puesto' => 'INGENIERO RESIDENTE',
                ],
                [
                    'codigo_fotocheck' => 'GC0000199',
                    'dni' => '71246409',
                    'nombres' => 'MANUEL DAVID',
                    'apellidos' => 'PESCORÁN CAMPOS',
                    'correo' => 'manuel.pescoran@grupocredco.com',
                    'telefono' => '963308915',
                    'happy_birthday' => '1996-07-22',
                    'fecha_ingreso' => '2023-12-04',
                    'puesto' => 'SUPERVISOR DE OBRAS CIVILES',
                ],
                [
                    'codigo_fotocheck' => 'GC0000308',
                    'dni' => '75494774',
                    'nombres' => 'ABEL FERNANDO',
                    'apellidos' => 'FIGUEROA PEREZ',
                    'correo' => 'abelfigueroaperez95@gmail.com',
                    'telefono' => '957590222',
                    'happy_birthday' => '1995-12-31',
                    'fecha_ingreso' => '2026-03-21',
                    'puesto' => 'SUPERVISOR DE OBRAS CIVILES',
                ],
                [
                    'codigo_fotocheck' => 'GC0000207',
                    'dni' => '72096059',
                    'nombres' => 'ALVARO JOSÉ',
                    'apellidos' => 'HUAYLLA LARREA',
                    'correo' => 'alvaro.huaylla@grupocredco.com',
                    'telefono' => '918564131',
                    'happy_birthday' => '1995-05-04',
                    'fecha_ingreso' => '2023-10-26',
                    'puesto' => 'SUPERVISOR DE SEGURIDAD',
                ],
                [
                    'codigo_fotocheck' => 'GC0000266',
                    'dni' => '75502801',
                    'nombres' => 'MOISES',
                    'apellidos' => 'ODAR RUIZ',
                    'correo' => 'odarrmoises@gmail.com',
                    'telefono' => '949523727',
                    'happy_birthday' => '2001-03-31',
                    'fecha_ingreso' => '2025-10-02',
                    'puesto' => 'SUPERVISOR DE SEGURIDAD',
                ],
                [
                    'codigo_fotocheck' => 'GC0000295',
                    'dni' => '72395332',
                    'nombres' => 'KEVIN ARNOLD',
                    'apellidos' => 'MALCA ROQUE',
                    'correo' => 'malca_28@hotmail.com',
                    'telefono' => '940128943',
                    'happy_birthday' => '1992-07-26',
                    'fecha_ingreso' => '2025-12-29',
                    'puesto' => 'ASISTENTE ADMINISTRATIVO',
                ],
                [
                    'codigo_fotocheck' => 'GC0000224',
                    'dni' => '46581212',
                    'nombres' => 'ALEXANDER',
                    'apellidos' => 'CHUNQUE PINEDO',
                    'correo' => 'Chunque_2012@hotmailcom',
                    'telefono' => '993157218',
                    'happy_birthday' => '1990-02-25',
                    'fecha_ingreso' => '2024-09-12',
                    'puesto' => 'CHOFER',
                ],
                [
                    'codigo_fotocheck' => 'GC0000305',
                    'dni' => '46807102',
                    'nombres' => 'JHON EDWARD',
                    'apellidos' => 'CHANDUVI CHUQUICAJAS',
                    'correo' => 'jon_tlv_acuario@hotmail.com',
                    'telefono' => '950399891',
                    'happy_birthday' => '1991-02-05',
                    'fecha_ingreso' => '2026-02-09',
                    'puesto' => 'CHOFER',
                ],
                [
                    'codigo_fotocheck' => 'GC0000016',
                    'dni' => '73036170',
                    'nombres' => 'RONAL MIKI',
                    'apellidos' => 'CARRANZA MISAHUAMAN',
                    'correo' => 'ronalcarranza1994@outlook.com',
                    'telefono' => '913852748',
                    'happy_birthday' => '1993-12-09',
                    'fecha_ingreso' => '2021-03-25',
                    'puesto' => 'CAPATAZ',
                ],
                [
                    'codigo_fotocheck' => 'GC0000071',
                    'dni' => '26731702',
                    'nombres' => 'NORBERTO',
                    'apellidos' => 'TERAN REVILLA',
                    'correo' => 'n06teran@gmail.com',
                    'telefono' => '951354747',
                    'happy_birthday' => '1977-06-06',
                    'fecha_ingreso' => '2021-07-29',
                    'puesto' => 'CAPATAZ',
                ],
                [
                    'codigo_fotocheck' => 'GC0000216',
                    'dni' => '71002403',
                    'nombres' => 'HEBER EFRAIN',
                    'apellidos' => 'ANTICONA ANTICONA',
                    'correo' => 'everanticona159@gmail.com',
                    'telefono' => '965451507',
                    'happy_birthday' => '2002-04-15',
                    'fecha_ingreso' => '2024-04-01',
                    'puesto' => 'OPERARIO CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000028',
                    'dni' => '70199652',
                    'nombres' => 'EDILBERTO',
                    'apellidos' => 'CAHUANA CHUQUIMANGO',
                    'correo' => 'edicahuanachuqimango@gmail.com',
                    'telefono' => '962744106',
                    'happy_birthday' => '1997-02-03',
                    'fecha_ingreso' => '2021-04-02',
                    'puesto' => 'OPERARIO CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000005',
                    'dni' => '47239686',
                    'nombres' => 'FRANKLIN',
                    'apellidos' => 'MISAHUAMAN BARDALES',
                    'correo' => 'Franklinmisahuamanbardales24@gmail.com',
                    'telefono' => '973455348',
                    'happy_birthday' => '1991-08-24',
                    'fecha_ingreso' => '2021-03-05',
                    'puesto' => 'OPERARIO CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000231',
                    'dni' => '48249505',
                    'nombres' => 'JORGE LUIS ANTONIO',
                    'apellidos' => 'RAMIREZ POMPA',
                    'correo' => 'Jorgeluisramirezpompa1@gmail.com',
                    'telefono' => '948526376',
                    'happy_birthday' => '1994-05-18',
                    'fecha_ingreso' => '2024-12-22',
                    'puesto' => 'OPERARIO CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000232',
                    'dni' => '75342164',
                    'nombres' => 'BRYAN DENNIS',
                    'apellidos' => 'ROJAS ABAD',
                    'correo' => 'Bryan_rojas2697@hotmail.com',
                    'telefono' => '938663062',
                    'happy_birthday' => '1997-12-26',
                    'fecha_ingreso' => '2024-12-22',
                    'puesto' => 'OPERARIO CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000007',
                    'dni' => '72444479',
                    'nombres' => 'ROSMA ROEL',
                    'apellidos' => 'ROJAS PEÑA',
                    'correo' => 'reykin.16@gmail.com',
                    'telefono' => '941260424',
                    'happy_birthday' => '1995-07-04',
                    'fecha_ingreso' => '2021-03-11',
                    'puesto' => 'OPERARIO CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000203',
                    'dni' => '47170380',
                    'nombres' => 'ELI',
                    'apellidos' => 'DURAN PINEDO',
                    'correo' => 'Elidu871@gmail.com',
                    'telefono' => '942281106',
                    'happy_birthday' => '1986-08-25',
                    'fecha_ingreso' => '2024-01-25',
                    'puesto' => 'OFICIAL CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000096',
                    'dni' => '73635435',
                    'nombres' => 'LUIS II',
                    'apellidos' => 'LINARES BLONDET',
                    'correo' => 'luislinaresb@hotmail.com',
                    'telefono' => '961749499',
                    'happy_birthday' => '1994-11-18',
                    'fecha_ingreso' => '2022-03-09',
                    'puesto' => 'OFICIAL CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000166',
                    'dni' => '71232355',
                    'nombres' => 'JAIME',
                    'apellidos' => 'LLAMOGA PINEDO',
                    'correo' => 'Llamogapinedoj@gmail.com',
                    'telefono' => '987654967',
                    'happy_birthday' => '1993-12-10',
                    'fecha_ingreso' => '2023-02-08',
                    'puesto' => 'OFICIAL CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000179',
                    'dni' => '43211300',
                    'nombres' => 'HILDEBRANDO',
                    'apellidos' => 'ROJAS GUERRERO',
                    'correo' => 'hilrojas1985@gmail.com',
                    'telefono' => '941205078',
                    'happy_birthday' => '1985-10-11',
                    'fecha_ingreso' => '2023-07-18',
                    'puesto' => 'OFICIAL CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000029',
                    'dni' => '41068253',
                    'nombres' => 'WALTER',
                    'apellidos' => 'SANCHEZ MOSQUEIRA',
                    'correo' => 'walter1134sanchez@gmail.com',
                    'telefono' => '999884640',
                    'happy_birthday' => '1979-07-01',
                    'fecha_ingreso' => '2021-04-02',
                    'puesto' => 'OFICIAL CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000212',
                    'dni' => '70137236',
                    'nombres' => 'GERSON YADER',
                    'apellidos' => 'TISNADO ARRESTEGUI',
                    'correo' => 'tisnadoarresteguig@gmail.com',
                    'telefono' => '960696017',
                    'happy_birthday' => '1999-02-01',
                    'fecha_ingreso' => '2024-03-02',
                    'puesto' => 'AYUDANTE CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000085',
                    'dni' => '71713031',
                    'nombres' => 'WILMER',
                    'apellidos' => 'ARIAS ARCE',
                    'correo' => 'Wilsonariasarce@gmail.com',
                    'telefono' => '982394253',
                    'happy_birthday' => '1995-06-18',
                    'fecha_ingreso' => '2021-12-15',
                    'puesto' => 'OFICIAL CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000114',
                    'dni' => '70210174',
                    'nombres' => 'YEISON ANTONI',
                    'apellidos' => 'ARRIBASPLATA ARRIBASPLATA',
                    'correo' => 'yeiz_123@hotmail.com',
                    'telefono' => '963513817',
                    'happy_birthday' => '1996-01-13',
                    'fecha_ingreso' => '2022-08-31',
                    'puesto' => 'AYUDANTE CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000118',
                    'dni' => '41534039',
                    'nombres' => 'OSWALDO',
                    'apellidos' => 'CARHUAPOMA VARGAS',
                    'correo' => 'Oswaldocarhuapoma27',
                    'telefono' => '971173092',
                    'happy_birthday' => '1982-08-18',
                    'fecha_ingreso' => '2022-09-14',
                    'puesto' => 'AYUDANTE CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000246',
                    'dni' => '47722881',
                    'nombres' => 'DIOVER YULINIO',
                    'apellidos' => 'CHUQUIMANGO RAMOS',
                    'correo' => 'yuliniochuquimango@gmail.com',
                    'telefono' => '993086901',
                    'happy_birthday' => '1993-04-02',
                    'fecha_ingreso' => '2025-03-27',
                    'puesto' => 'AYUDANTE CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000241',
                    'dni' => '47697810',
                    'nombres' => 'BRUNO',
                    'apellidos' => 'DELAO TORRES',
                    'correo' => 'brunodelaotorres25@gmail.com',
                    'telefono' => '963544564',
                    'happy_birthday' => '1991-01-25',
                    'fecha_ingreso' => '2025-02-06',
                    'puesto' => 'AYUDANTE CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000221',
                    'dni' => '72944466',
                    'nombres' => 'BENAVIDES',
                    'apellidos' => 'JARA DE LA CRUZ',
                    'correo' => 'jarabenavides7@gmail.com',
                    'telefono' => '932298906',
                    'happy_birthday' => '1998-02-03',
                    'fecha_ingreso' => '2024-07-18',
                    'puesto' => 'OFICIAL CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000186',
                    'dni' => '74206233',
                    'nombres' => 'JAIME LUIS',
                    'apellidos' => 'LLANOS LOPEZ',
                    'correo' => 'luisllanos077@gmail.com',
                    'telefono' => '997573190',
                    'happy_birthday' => '1995-10-28',
                    'fecha_ingreso' => '2023-09-13',
                    'puesto' => 'AYUDANTE CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000182',
                    'dni' => '71758207',
                    'nombres' => 'WILLIAM ALI',
                    'apellidos' => 'LINARES RAMIREZ',
                    'correo' => 'wlinare907@gmail.com',
                    'telefono' => '997497655',
                    'happy_birthday' => '1998-02-20',
                    'fecha_ingreso' => '2023-08-16',
                    'puesto' => 'OFICIAL CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000201',
                    'dni' => '76352395',
                    'nombres' => 'SEGUNDO EDUARDO',
                    'apellidos' => 'MIRANDA GALLARDO',
                    'correo' => 'middle-e@hotmail.com',
                    'telefono' => '980269415',
                    'happy_birthday' => '1996-04-26',
                    'fecha_ingreso' => '2024-01-25',
                    'puesto' => 'AYUDANTE CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000191',
                    'dni' => '74083999',
                    'nombres' => 'JHONATAN KEVIN',
                    'apellidos' => 'PISCO PINEDO',
                    'correo' => 'jonathankevinpiscopinedo@gmail.com',
                    'telefono' => '965057215',
                    'happy_birthday' => '2000-11-26',
                    'fecha_ingreso' => '2023-10-11',
                    'puesto' => 'AYUDANTE CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000227',
                    'dni' => '44425798',
                    'nombres' => 'SANTOS',
                    'apellidos' => 'TANTA DE LA CRUZ',
                    'correo' => 'santostantadelacruz625@gmail.com',
                    'telefono' => '936586186',
                    'happy_birthday' => '1987-08-18',
                    'fecha_ingreso' => '2024-11-07',
                    'puesto' => 'AYUDANTE CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000252',
                    'dni' => '75061706',
                    'nombres' => 'YOEL',
                    'apellidos' => 'DUCOS INFANTE',
                    'correo' => 'ducosyoel@gmail.com',
                    'telefono' => '983244796',
                    'happy_birthday' => '2001-11-03',
                    'fecha_ingreso' => '2025-05-22',
                    'puesto' => 'AYUDANTE CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000254',
                    'dni' => '72882534',
                    'nombres' => 'ROBERTO ALEXANDER',
                    'apellidos' => 'VENTURA ARRIBASPLATA',
                    'correo' => 'rventuraa15@unc.edu.pe',
                    'telefono' => '979086341',
                    'happy_birthday' => '1995-12-18',
                    'fecha_ingreso' => '2025-05-22',
                    'puesto' => 'AYUDANTE CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000251',
                    'dni' => '47482732',
                    'nombres' => 'VICTOR ABEL',
                    'apellidos' => 'ALVARADO SANCHEZ',
                    'correo' => 'victoralvaradovale2020@gmail.com',
                    'telefono' => '944017196',
                    'happy_birthday' => '1991-06-12',
                    'fecha_ingreso' => '2025-05-22',
                    'puesto' => 'OPERARIO CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000255',
                    'dni' => '74230580',
                    'nombres' => 'JHONATAN ALEXANDER',
                    'apellidos' => 'HUAMAN RAMIREZ',
                    'correo' => 'huamanramirezjhon96@gmail.com',
                    'telefono' => '933470962',
                    'happy_birthday' => '2002-06-20',
                    'fecha_ingreso' => '2025-05-24',
                    'puesto' => 'AYUDANTE CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000256',
                    'dni' => '71820793',
                    'nombres' => 'JORGE LUIS',
                    'apellidos' => 'CERDAN CORO',
                    'correo' => 'cerdancorojorgeluis@gmail.com',
                    'telefono' => '939987078',
                    'happy_birthday' => '1995-06-23',
                    'fecha_ingreso' => '2025-06-20',
                    'puesto' => 'AYUDANTE CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000257',
                    'dni' => '71738277',
                    'nombres' => 'EDINSON YAIR',
                    'apellidos' => 'CERDAN CORO',
                    'correo' => 'yaircerdan770@gmail.com',
                    'telefono' => '939987078',
                    'happy_birthday' => '1998-03-14',
                    'fecha_ingreso' => '2025-07-17',
                    'puesto' => 'AYUDANTE CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000258',
                    'dni' => '79994041',
                    'nombres' => 'HERMAN MILER',
                    'apellidos' => 'BARDALES ARCE',
                    'correo' => 'MILERBARDALESARCE1@GMAIL.COM',
                    'telefono' => '942346607',
                    'happy_birthday' => '1998-06-16',
                    'fecha_ingreso' => '2025-07-24',
                    'puesto' => 'AYUDANTE CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000260',
                    'dni' => '71201370',
                    'nombres' => 'WILMAN PABLO',
                    'apellidos' => 'GONZALES ALVARADO',
                    'correo' => 'PABLOGONZALESALVARADO@GMAIL.COM',
                    'telefono' => '940759180',
                    'happy_birthday' => '1992-10-06',
                    'fecha_ingreso' => '2025-09-04',
                    'puesto' => 'AYUDANTE CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000263',
                    'dni' => '47656213',
                    'nombres' => 'CARLOS ALFREDO',
                    'apellidos' => 'LLARO TORIBIO',
                    'correo' => 'llarotoribiocarlos@mail.com',
                    'telefono' => '958664280',
                    'happy_birthday' => '1992-01-25',
                    'fecha_ingreso' => '2025-09-18',
                    'puesto' => 'AYUDANTE CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000268',
                    'dni' => '47988649',
                    'nombres' => 'ABRAHAM',
                    'apellidos' => 'MENA QUILICHE',
                    'correo' => 'menaquiliceabraham@gamil.com',
                    'telefono' => '901621652',
                    'happy_birthday' => '1993-10-08',
                    'fecha_ingreso' => '2025-10-16',
                    'puesto' => 'AYUDANTE CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000271',
                    'dni' => '70671905',
                    'nombres' => 'EDGAR',
                    'apellidos' => 'LÓPEZ VASQUEZ',
                    'correo' => 'lopezvasqueze55@gmail.com',
                    'telefono' => '965260549',
                    'happy_birthday' => '2000-07-06',
                    'fecha_ingreso' => '2025-10-18',
                    'puesto' => 'AYUDANTE CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000274',
                    'dni' => '71403297',
                    'nombres' => 'CRISTIAN JHOEL',
                    'apellidos' => 'FLORES CARMONA',
                    'correo' => 'Joel1123carmona@gmail.com',
                    'telefono' => '917110810',
                    'happy_birthday' => '1997-09-17',
                    'fecha_ingreso' => '2025-10-25',
                    'puesto' => 'AYUDANTE CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000275',
                    'dni' => '23010328',
                    'nombres' => 'CESAR EDUARDO',
                    'apellidos' => 'CORTEZ CERQUIN',
                    'correo' => 'EduardoCC_333@hotmail.com',
                    'telefono' => '990854966',
                    'happy_birthday' => '2025-11-01',
                    'fecha_ingreso' => '2025-11-01',
                    'puesto' => 'AYUDANTE CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000276',
                    'dni' => '44332482',
                    'nombres' => 'LESEM YONATAN',
                    'apellidos' => 'INFANTE GUEVARA',
                    'correo' => 'Leseminfante@gmail.com',
                    'telefono' => '96133843',
                    'happy_birthday' => '1986-03-20',
                    'fecha_ingreso' => '2025-10-30',
                    'puesto' => 'AYUDANTE CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000277',
                    'dni' => '77425660',
                    'nombres' => 'JUAN',
                    'apellidos' => 'PACHAMANGO DIAZ',
                    'correo' => 'Juanpachamangodiaz66@gmail.com',
                    'telefono' => '99247095',
                    'happy_birthday' => '2001-11-01',
                    'fecha_ingreso' => '2025-11-01',
                    'puesto' => 'AYUDANTE CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000278',
                    'dni' => '45346039',
                    'nombres' => 'HERMAN DOMINGO',
                    'apellidos' => 'PEREZ RODAS',
                    'correo' => 'hermanperez914@gmail.com',
                    'telefono' => '97875157',
                    'happy_birthday' => '1980-12-20',
                    'fecha_ingreso' => '2025-11-01',
                    'puesto' => 'AYUDANTE CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000279',
                    'dni' => '77705545',
                    'nombres' => 'JHOM FRANKLIN',
                    'apellidos' => 'VARGAS URBINA',
                    'correo' => 'jhomurbina08@gmail.com',
                    'telefono' => '935608207',
                    'happy_birthday' => '1996-01-02',
                    'fecha_ingreso' => '2025-10-30',
                    'puesto' => 'AYUDANTE CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000280',
                    'dni' => '76862919',
                    'nombres' => 'MANUEL',
                    'apellidos' => 'SORIANO TANTA',
                    'correo' => 'sorianotantamanuel@gmail.com',
                    'telefono' => '941280713',
                    'happy_birthday' => '2000-09-18',
                    'fecha_ingreso' => '2025-11-06',
                    'puesto' => 'AYUDANTE CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000282',
                    'dni' => '46790663',
                    'nombres' => 'WILLIAM JOEL',
                    'apellidos' => 'VASQUEZ HUAMAN',
                    'correo' => 'joel19_45@gmail.com',
                    'telefono' => '955769367',
                    'happy_birthday' => '1991-02-08',
                    'fecha_ingreso' => '2025-11-06',
                    'puesto' => 'AYUDANTE CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000285',
                    'dni' => '73828995',
                    'nombres' => 'DIEGO LEONEL',
                    'apellidos' => 'VIVANCO LEON',
                    'correo' => 'diegovivancol220704@gmail.com',
                    'telefono' => '914764014',
                    'happy_birthday' => '2004-07-22',
                    'fecha_ingreso' => '2025-11-27',
                    'puesto' => 'AYUDANTE CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000286',
                    'dni' => '71140416',
                    'nombres' => 'GLEISER ANIBAL',
                    'apellidos' => 'ESPINOZA RODAS',
                    'correo' => 'gleiserespinozarodas@gmail.com',
                    'telefono' => '947030035',
                    'happy_birthday' => '1997-11-24',
                    'fecha_ingreso' => '2025-11-27',
                    'puesto' => 'AYUDANTE CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000287',
                    'dni' => '41287709',
                    'nombres' => 'ROBERTO',
                    'apellidos' => 'TACILLA CHAUPE',
                    'correo' => 'tacillachaupe-13@gmail.com',
                    'telefono' => '978685983',
                    'happy_birthday' => '1981-09-13',
                    'fecha_ingreso' => '2025-11-29',
                    'puesto' => 'AYUDANTE CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000288',
                    'dni' => '75716081',
                    'nombres' => 'PEDRO',
                    'apellidos' => 'SALAZAR CHILON',
                    'correo' => 'Pedrosalazarchilon40@gmail.com',
                    'telefono' => '910726599',
                    'happy_birthday' => '1995-02-07',
                    'fecha_ingreso' => '2025-12-11',
                    'puesto' => 'AYUDANTE CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000289',
                    'dni' => '71766968',
                    'nombres' => 'JESUS DAVID',
                    'apellidos' => 'CASTREJON CASTREJON',
                    'correo' => 'davidcastrejoncastrejon65@gmail.com',
                    'telefono' => '921194256',
                    'happy_birthday' => '1999-08-07',
                    'fecha_ingreso' => '2025-12-18',
                    'puesto' => 'OFICIAL CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000290',
                    'dni' => '73255244',
                    'nombres' => 'CESAR CARLOS',
                    'apellidos' => 'NARRO BRINGAS',
                    'correo' => 'cnarro162@gmail.com',
                    'telefono' => '980806969',
                    'happy_birthday' => '2000-10-18',
                    'fecha_ingreso' => '2025-12-18',
                    'puesto' => 'AYUDANTE CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000296',
                    'dni' => '73427626',
                    'nombres' => 'JASON JOEL',
                    'apellidos' => 'VASQUEZ MESTANZA',
                    'correo' => '12dragonjoel@gmail.com',
                    'telefono' => '933020329',
                    'happy_birthday' => '1993-03-27',
                    'fecha_ingreso' => '2026-01-01',
                    'puesto' => 'AYUDANTE CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000299',
                    'dni' => '48321481',
                    'nombres' => 'ELVIS',
                    'apellidos' => 'VASQUEZ LARA',
                    'correo' => 'avasquez16_1@unc.edu.pe',
                    'telefono' => '974662698',
                    'happy_birthday' => '1994-06-09',
                    'fecha_ingreso' => '2026-01-29',
                    'puesto' => 'AYUDANTE CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000300',
                    'dni' => '47936122',
                    'nombres' => 'ANTONY YADIN',
                    'apellidos' => 'MENDOZA CHUQUILIN',
                    'correo' => 'antonysanmateo08@gmail.com',
                    'telefono' => '918961794',
                    'happy_birthday' => '1993-08-01',
                    'fecha_ingreso' => '2026-02-05',
                    'puesto' => 'AYUDANTE CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000301',
                    'dni' => '77661329',
                    'nombres' => 'NIXON ANDERZON',
                    'apellidos' => 'GUEVARA MENDOZA',
                    'correo' => 'nixonguevaramendoza@gmail.com',
                    'telefono' => '921485291',
                    'happy_birthday' => '2004-05-09',
                    'fecha_ingreso' => '2026-02-05',
                    'puesto' => 'AYUDANTE CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000302',
                    'dni' => '75982158',
                    'nombres' => 'ELISER MANUEL',
                    'apellidos' => 'DIAZ RAMOS',
                    'correo' => 'elidiaz54ramos@gmail.com',
                    'telefono' => '919050922',
                    'happy_birthday' => '2003-05-24',
                    'fecha_ingreso' => '2026-02-12',
                    'puesto' => 'AYUDANTE CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000303',
                    'dni' => '47541002',
                    'nombres' => 'ABNER JOSIAS',
                    'apellidos' => 'CHUQUILIN MENDOZA',
                    'correo' => 'chmabner@gmail.com',
                    'telefono' => '975134067',
                    'happy_birthday' => '1992-12-26',
                    'fecha_ingreso' => '2026-02-14',
                    'puesto' => 'AYUDANTE CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000304',
                    'dni' => '77153776',
                    'nombres' => 'WILSON',
                    'apellidos' => 'CHAVEZ INFANTE',
                    'correo' => 'chavezinfantewilson936@gmail.com',
                    'telefono' => '973251999',
                    'happy_birthday' => '1995-08-12',
                    'fecha_ingreso' => '2026-03-06',
                    'puesto' => 'AYUDANTE CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000306',
                    'dni' => '71788180',
                    'nombres' => 'HUMBERTO',
                    'apellidos' => 'MARTINEZ HUAMAN',
                    'correo' => 'martinezhuamanhumberto4@gmail.com',
                    'telefono' => '957564332',
                    'happy_birthday' => '2004-02-19',
                    'fecha_ingreso' => '2026-03-06',
                    'puesto' => 'AYUDANTE CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000307',
                    'dni' => '70399270',
                    'nombres' => 'NEULER',
                    'apellidos' => 'CHUQUILIN BECERRA',
                    'correo' => 'neulercitochuquilinj@gmail.com',
                    'telefono' => '920991413',
                    'happy_birthday' => '1998-02-19',
                    'fecha_ingreso' => '2026-03-07',
                    'puesto' => 'AYUDANTE CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000309',
                    'dni' => '46386955',
                    'nombres' => 'CRISTIAN EDUARDO',
                    'apellidos' => 'HERMENEGILDO GRADOS',
                    'correo' => 'hermenegildogradosc@gmail.com',
                    'telefono' => '920991414',
                    'happy_birthday' => '1989-07-29',
                    'fecha_ingreso' => '2026-03-26',
                    'puesto' => 'AYUDANTE CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000310',
                    'dni' => '60133977',
                    'nombres' => 'ANTENOR',
                    'apellidos' => 'SALDAÑA VALDIVIA',
                    'correo' => 'antenorsaldanavaldivia2@gmail.com',
                    'telefono' => '967569903',
                    'happy_birthday' => '2005-08-03',
                    'fecha_ingreso' => '2026-03-26',
                    'puesto' => 'AYUDANTE CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000311',
                    'dni' => '43556397',
                    'nombres' => 'PERCY',
                    'apellidos' => 'HUAMAN CUEVA',
                    'correo' => 'huamancuevapercy@gmail.com',
                    'telefono' => '943202916',
                    'happy_birthday' => '1986-03-09',
                    'fecha_ingreso' => '2026-04-02',
                    'puesto' => 'OPERARIO CIVIL',
                ],
                [
                    'codigo_fotocheck' => 'GC0000312',
                    'dni' => '43613307',
                    'nombres' => 'DIONICIO',
                    'apellidos' => 'TANTA CHUQUIMANGO',
                    'correo' => 'dioniciotantachuquimango@gmail.com',
                    'telefono' => '991400514',
                    'happy_birthday' => '1986-07-04',
                    'fecha_ingreso' => '2026-04-04',
                    'puesto' => 'OFICIAL CIVIL',
                ],
            ];

            foreach ($trabajadores as $trabajador) {
                $puesto = $trabajador['puesto'];
                unset($trabajador['puesto']);

                $cargoKey = $normalizar($puesto);

                if (! isset($cargoIds[$cargoKey])) {
                    throw new RuntimeException('No existe el cargo laboral: ' . $puesto);
                }

                DB::table('trabajadores')->updateOrInsert(
                    ['dni' => $trabajador['dni']],
                    array_merge($trabajador, [
                        'proyecto_id' => $proyecto->id,
                        'cargo_laboral_id' => $cargoIds[$cargoKey],
                        'fecha_cese' => null,
                        'estado' => $estadoActivo,
                        'foto_url' => null,
                        'created_at' => $now,
                        'updated_at' => $now,
                    ])
                );
            }
        });
    }
}